# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: stuff i do

description: Stylish Jekyll Theme
author:
  name: twistdroach
  email: 521e5fca@opayq.com
  github: twistdroach
  twitter: twistdroach
#  pinterest: asd123
  linkedin: asd123
  bio: twistdroach
  email_md5: b867bfbbfd4304e2dd13f208cec1aa49

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
