# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md", "test_launch.sh"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: Zachary D. Rowitsch

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: stuff i do

description: Stylish Jekyll Theme
author:
  name: twistdroach
  email: 521e5fca@opayq.com
  github: twistdroach
#  twitter: twistdroach
#  pinterest: asd123
  linkedin: zrowitsch
  bio: Father, leader, software developer
  email_md5: b867bfbbfd4304e2dd13f208cec1aa49

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
computers_path: vintage_computers.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

collections:
  computer_entries:
    sort_by: introduction_date

plugins:
  - jekyll-paginate
